version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todolistdb
      MYSQL_USER: user123
      MYSQL_PASSWORD: user123
    ports:
      - "3307:3306"

  app:
    build: .
    container_name: todolist-app
    ports:
      - "8000:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todolistdb
      SPRING_DATASOURCE_USERNAME: user123
      SPRING_DATASOURCE_PASSWORD: user123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - mysql
